"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Optional
from e2b.exceptions import SandboxException

Stdout = str
Stderr = str
PtyOutput = bytes
@dataclass
class PtySize:
    """
    Pseudo-terminal size.
    """
    rows: int
    cols: int
    ...


@dataclass
class CommandResult:
    """
    Command execution result.
    """
    stderr: str
    stdout: str
    exit_code: int
    error: Optional[str]
    ...


@dataclass
class CommandExitException(SandboxException, CommandResult):
    """
    Exception raised when a command exits with a non-zero exit code.
    """
    def __str__(self) -> str:
        ...
    


