"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Dict, List, Optional

@dataclass
class ProcessInfo:
    """
    Information about a command, PTY session or start command running in the sandbox as process.
    """
    pid: int
    tag: Optional[str]
    cmd: str
    args: List[str]
    envs: Dict[str, str]
    cwd: Optional[str]
    ...


