"""
This type stub file was generated by pyright.
"""

def format_sandbox_timeout_exception(message: str): # -> TimeoutException:
    ...

def format_request_timeout_error() -> Exception:
    ...

def format_execution_timeout_error() -> Exception:
    ...

class SandboxException(Exception):
    """
    Base class for all sandbox errors.

    Raised when a general sandbox exception occurs.
    """
    ...


class TimeoutException(SandboxException):
    """
    Raised when a timeout occurs.

    The `unavailable` exception type is caused by sandbox timeout.\n
    The `canceled` exception type is caused by exceeding request timeout.\n
    The `deadline_exceeded` exception type is caused by exceeding the timeout for process, watch, etc.\n
    The `unknown` exception type is sometimes caused by the sandbox timeout when the request is not processed correctly.\n
    """
    ...


class InvalidArgumentException(SandboxException):
    """
    Raised when an invalid argument is provided.
    """
    ...


class NotEnoughSpaceException(SandboxException):
    """
    Raised when there is not enough disk space.
    """
    ...


class NotFoundException(SandboxException):
    """
    Raised when a resource is not found.
    """
    ...


class AuthenticationException(Exception):
    """
    Raised when authentication fails.
    """
    ...


class TemplateException(SandboxException):
    """
    Exception raised when the template uses old envd version. It isn't compatible with the new SDK.
    """
    ...


class RateLimitException(SandboxException):
    """
    Raised when the API rate limit is exceeded.
    """
    ...


