"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from typing import IO, Optional, TypedDict, Union
from e2b.envd.filesystem import filesystem_pb2

class FileType(Enum):
    """
    Enum representing the type of filesystem object.
    """
    FILE = ...
    DIR = ...


def map_file_type(ft: filesystem_pb2.FileType): # -> Literal[FileType.FILE, FileType.DIR] | None:
    ...

@dataclass
class WriteInfo:
    """
    Sandbox filesystem object information.
    """
    name: str
    type: Optional[FileType]
    path: str
    ...


@dataclass
class EntryInfo(WriteInfo):
    """
    Extended sandbox filesystem object information.
    """
    size: int
    mode: int
    permissions: str
    owner: str
    group: str
    modified_time: datetime
    symlink_target: Optional[str] = ...


class WriteEntry(TypedDict):
    """
    Contains path and data of the file to be written to the filesystem.
    """
    path: str
    data: Union[str, bytes, IO]
    ...


