"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from enum import Enum
from e2b.envd.filesystem.filesystem_pb2 import EventType

class FilesystemEventType(Enum):
    """
    Enum representing the type of filesystem event.
    """
    CHMOD = ...
    CREATE = ...
    REMOVE = ...
    RENAME = ...
    WRITE = ...


def map_event_type(event: EventType): # -> Literal[FilesystemEventType.CHMOD, FilesystemEventType.CREATE, FilesystemEventType.REMOVE, FilesystemEventType.RENAME, FilesystemEventType.WRITE] | None:
    ...

@dataclass
class FilesystemEvent:
    """
    Contains information about the filesystem event - the name of the file and the type of the event.
    """
    name: str
    type: FilesystemEventType
    ...


