"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Dict, Optional
from typing_extensions import Unpack
from datetime import datetime
from e2b.api.client.models import SandboxState
from e2b.connection_config import ApiParams

@dataclass
class SandboxInfo:
    """Information about a sandbox."""
    sandbox_id: str
    sandbox_domain: Optional[str]
    template_id: str
    name: Optional[str]
    metadata: Dict[str, str]
    started_at: datetime
    end_at: datetime
    state: SandboxState
    cpu_count: int
    memory_mb: int
    envd_version: str
    _envd_access_token: Optional[str]
    ...


@dataclass
class SandboxQuery:
    """Query parameters for listing sandboxes."""
    metadata: Optional[dict[str, str]] = ...
    state: Optional[list[SandboxState]] = ...


@dataclass
class SandboxMetrics:
    """Sandbox metrics."""
    cpu_count: int
    cpu_used_pct: float
    disk_total: int
    disk_used: int
    mem_total: int
    mem_used: int
    timestamp: datetime
    ...


class SandboxPaginatorBase:
    def __init__(self, query: Optional[SandboxQuery] = ..., limit: Optional[int] = ..., next_token: Optional[str] = ..., **opts: Unpack[ApiParams]) -> None:
        ...
    
    @property
    def has_next(self) -> bool:
        """
        Returns True if there are more items to fetch.
        """
        ...
    
    @property
    def next_token(self) -> Optional[str]:
        """
        Returns the next token to use for pagination.
        """
        ...
    


