"""
This type stub file was generated by pyright.
"""

from typing import Literal, Optional, TypedDict

Operation = Literal["read", "write"]
class Signature(TypedDict):
    signature: str
    expiration: Optional[int]
    ...


def get_signature(path: str, operation: Operation, user: str, envd_access_token: Optional[str], expiration_in_seconds: Optional[int] = ...) -> Signature:
    """
    Generate a v1 signature for sandbox file URLs.
    """
    ...

