"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional, Type, TypeVar

T = TypeVar("T")
class class_method_variant:
    def __init__(self, class_method_name) -> None:
        ...
    
    method: Any
    def __call__(self, method: T) -> T:
        ...
    
    def __get__(self, obj, objtype: Optional[Type[Any]] = ...): # -> _Wrapped[Callable[..., Any], Any, Callable[..., Any], Any]:
        ...
    


