"""
This type stub file was generated by pyright.
"""

import httpx

ENVD_API_FILES_ROUTE = ...
ENVD_API_HEALTH_ROUTE = ...
def get_message(e: httpx.Response) -> str:
    ...

def handle_envd_api_exception(res: httpx.Response): # -> InvalidArgumentException | AuthenticationException | NotFoundException | SandboxException | TimeoutException | NotEnoughSpaceException | None:
    ...

async def ahandle_envd_api_exception(res: httpx.Response): # -> InvalidArgumentException | AuthenticationException | NotFoundException | SandboxException | TimeoutException | NotEnoughSpaceException | None:
    ...

def format_envd_api_exception(status_code: int, message: str): # -> InvalidArgumentException | AuthenticationException | NotFoundException | SandboxException | TimeoutException | NotEnoughSpaceException:
    ...

