"""
This type stub file was generated by pyright.
"""

from typing import Optional
from e2b.connection_config import Username

def handle_rpc_exception(e: Exception): # -> InvalidArgumentException | AuthenticationException | NotFoundException | TimeoutException | RateLimitException | SandboxException | Exception:
    ...

def authentication_header(user: Optional[Username] = ...): # -> dict[str, str]:
    ...

