"""
This type stub file was generated by pyright.
"""

from typing import List
from e2b.envd.filesystem import filesystem_connect
from e2b.sandbox.filesystem.watch_handle import FilesystemEvent

class WatchHandle:
    """
    Handle for watching filesystem events.
    It is used to get the latest events that have occurred in the watched directory.

    Use `.stop()` to stop watching the directory.
    """
    def __init__(self, rpc: filesystem_connect.FilesystemClient, watcher_id: str) -> None:
        ...
    
    def stop(self): # -> None:
        """
        Stop watching the directory.
        After you stop the watcher you won't be able to get the events anymore.
        """
        ...
    
    def get_new_events(self) -> List[FilesystemEvent]:
        """
        Get the latest events that have occurred in the watched directory since the last call, or from the beginning of the watching, up until now.

        :return: List of filesystem events
        """
        ...
    


