"""
This type stub file was generated by pyright.
"""

from typing import Optional
from typing_extensions import Unpack
from e2b.sandbox.sandbox_api import SandboxQuery
from e2b.sandbox.main import SandboxBase
from e2b.connection_config import ApiParams
from e2b.sandbox_sync.paginator import SandboxPaginator

class SandboxApi(SandboxBase):
    @staticmethod
    def list(query: Optional[SandboxQuery] = ..., limit: Optional[int] = ..., next_token: Optional[str] = ..., **opts: Unpack[ApiParams]) -> SandboxPaginator:
        """
        List all running sandboxes.

        :param query: Filter the list of sandboxes by metadata or state, e.g. `SandboxListQuery(metadata={"key": "value"})` or `SandboxListQuery(state=[SandboxState.RUNNING])`
        :param limit: Maximum number of sandboxes to return per page
        :param next_token: Token for pagination

        :return: List of running sandboxes
        """
        ...
    


