"""
This type stub file was generated by pyright.
"""

from typing import Optional, Union
from ...client import AuthenticatedClient
from ...models.error import Error
from ...models.log_level import LogLevel
from ...models.template_build import TemplateBuild
from ...types import Response, Unset

def sync_detailed(template_id: str, build_id: str, *, client: AuthenticatedClient, logs_offset: Union[Unset, int] = ..., level: Union[Unset, LogLevel] = ...) -> Response[Union[Error, TemplateBuild]]:
    """Get template build info

    Args:
        template_id (str):
        build_id (str):
        logs_offset (Union[Unset, int]):  Default: 0.
        level (Union[Unset, LogLevel]): State of the sandbox

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Union[Error, TemplateBuild]]
    """
    ...

def sync(template_id: str, build_id: str, *, client: AuthenticatedClient, logs_offset: Union[Unset, int] = ..., level: Union[Unset, LogLevel] = ...) -> Optional[Union[Error, TemplateBuild]]:
    """Get template build info

    Args:
        template_id (str):
        build_id (str):
        logs_offset (Union[Unset, int]):  Default: 0.
        level (Union[Unset, LogLevel]): State of the sandbox

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Union[Error, TemplateBuild]
    """
    ...

async def asyncio_detailed(template_id: str, build_id: str, *, client: AuthenticatedClient, logs_offset: Union[Unset, int] = ..., level: Union[Unset, LogLevel] = ...) -> Response[Union[Error, TemplateBuild]]:
    """Get template build info

    Args:
        template_id (str):
        build_id (str):
        logs_offset (Union[Unset, int]):  Default: 0.
        level (Union[Unset, LogLevel]): State of the sandbox

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Union[Error, TemplateBuild]]
    """
    ...

async def asyncio(template_id: str, build_id: str, *, client: AuthenticatedClient, logs_offset: Union[Unset, int] = ..., level: Union[Unset, LogLevel] = ...) -> Optional[Union[Error, TemplateBuild]]:
    """Get template build info

    Args:
        template_id (str):
        build_id (str):
        logs_offset (Union[Unset, int]):  Default: 0.
        level (Union[Unset, LogLevel]): State of the sandbox

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Union[Error, TemplateBuild]
    """
    ...

