"""
This type stub file was generated by pyright.
"""

from typing import Optional, Union
from ...client import AuthenticatedClient
from ...models.error import Error
from ...models.template_build_file_upload import TemplateBuildFileUpload
from ...types import Response

def sync_detailed(template_id: str, hash_: str, *, client: AuthenticatedClient) -> Response[Union[Error, TemplateBuildFileUpload]]:
    """Get an upload link for a tar file containing build layer files

    Args:
        template_id (str):
        hash_ (str): Hash of the files

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Union[Error, TemplateBuildFileUpload]]
    """
    ...

def sync(template_id: str, hash_: str, *, client: AuthenticatedClient) -> Optional[Union[Error, TemplateBuildFileUpload]]:
    """Get an upload link for a tar file containing build layer files

    Args:
        template_id (str):
        hash_ (str): Hash of the files

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Union[Error, TemplateBuildFileUpload]
    """
    ...

async def asyncio_detailed(template_id: str, hash_: str, *, client: AuthenticatedClient) -> Response[Union[Error, TemplateBuildFileUpload]]:
    """Get an upload link for a tar file containing build layer files

    Args:
        template_id (str):
        hash_ (str): Hash of the files

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Union[Error, TemplateBuildFileUpload]]
    """
    ...

async def asyncio(template_id: str, hash_: str, *, client: AuthenticatedClient) -> Optional[Union[Error, TemplateBuildFileUpload]]:
    """Get an upload link for a tar file containing build layer files

    Args:
        template_id (str):
        hash_ (str): Hash of the files

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Union[Error, TemplateBuildFileUpload]
    """
    ...

