"""
This type stub file was generated by pyright.
"""

from typing import Optional, Union
from ...client import AuthenticatedClient
from ...models.error import Error
from ...models.template import Template
from ...models.template_build_request_v2 import TemplateBuildRequestV2
from ...types import Response

def sync_detailed(*, client: AuthenticatedClient, body: TemplateBuildRequestV2) -> Response[Union[Error, Template]]:
    """Create a new template

    Args:
        body (TemplateBuildRequestV2):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Union[Error, Template]]
    """
    ...

def sync(*, client: AuthenticatedClient, body: TemplateBuildRequestV2) -> Optional[Union[Error, Template]]:
    """Create a new template

    Args:
        body (TemplateBuildRequestV2):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Union[Error, Template]
    """
    ...

async def asyncio_detailed(*, client: AuthenticatedClient, body: TemplateBuildRequestV2) -> Response[Union[Error, Template]]:
    """Create a new template

    Args:
        body (TemplateBuildRequestV2):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Union[Error, Template]]
    """
    ...

async def asyncio(*, client: AuthenticatedClient, body: TemplateBuildRequestV2) -> Optional[Union[Error, Template]]:
    """Create a new template

    Args:
        body (TemplateBuildRequestV2):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Union[Error, Template]
    """
    ...

