"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional, Union
from ...client import AuthenticatedClient
from ...models.error import Error
from ...models.template_build_start_v2 import TemplateBuildStartV2
from ...types import Response

def sync_detailed(template_id: str, build_id: str, *, client: AuthenticatedClient, body: TemplateBuildStartV2) -> Response[Union[Any, Error]]:
    """Start the build

    Args:
        template_id (str):
        build_id (str):
        body (TemplateBuildStartV2):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Union[Any, Error]]
    """
    ...

def sync(template_id: str, build_id: str, *, client: AuthenticatedClient, body: TemplateBuildStartV2) -> Optional[Union[Any, Error]]:
    """Start the build

    Args:
        template_id (str):
        build_id (str):
        body (TemplateBuildStartV2):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Union[Any, Error]
    """
    ...

async def asyncio_detailed(template_id: str, build_id: str, *, client: AuthenticatedClient, body: TemplateBuildStartV2) -> Response[Union[Any, Error]]:
    """Start the build

    Args:
        template_id (str):
        build_id (str):
        body (TemplateBuildStartV2):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Union[Any, Error]]
    """
    ...

async def asyncio(template_id: str, build_id: str, *, client: AuthenticatedClient, body: TemplateBuildStartV2) -> Optional[Union[Any, Error]]:
    """Start the build

    Args:
        template_id (str):
        build_id (str):
        body (TemplateBuildStartV2):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Union[Any, Error]
    """
    ...

