"""
This type stub file was generated by pyright.
"""

from typing import Callable, List, Optional
from types import TracebackType
from e2b.template.types import LogEntry, TemplateType
from e2b.api.client.client import AuthenticatedClient
from e2b.api.client.models import TemplateBuild, TemplateBuildFileUpload

async def request_build(client: AuthenticatedClient, name: str, cpu_count: int, memory_mb: int): # -> Template:
    ...

async def get_file_upload_link(client: AuthenticatedClient, template_id: str, files_hash: str, stack_trace: Optional[TracebackType] = ...) -> TemplateBuildFileUpload:
    ...

async def upload_file(file_name: str, context_path: str, url: str, stack_trace: Optional[TracebackType] = ...): # -> None:
    ...

async def trigger_build(client: AuthenticatedClient, template_id: str, build_id: str, template: TemplateType) -> None:
    ...

async def get_build_status(client: AuthenticatedClient, template_id: str, build_id: str, logs_offset: int) -> TemplateBuild:
    ...

async def wait_for_build_finish(client: AuthenticatedClient, template_id: str, build_id: str, on_build_logs: Optional[Callable[[LogEntry], None]] = ..., logs_refresh_frequency: float = ..., stack_traces: List[TracebackType] = ...): # -> None:
    ...

