"""
This type stub file was generated by pyright.
"""

from typing import Callable, Optional
from e2b.template.main import TemplateBase, TemplateClass
from e2b.template.types import LogEntry

class AsyncTemplate(TemplateBase):
    @staticmethod
    async def build(template: TemplateClass, alias: str, cpu_count: int = ..., memory_mb: int = ..., skip_cache: bool = ..., on_build_logs: Optional[Callable[[LogEntry], None]] = ..., api_key: Optional[str] = ..., domain: Optional[str] = ...) -> None:
        ...
    


