"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional, Union
from ...client import AuthenticatedClient
from ...models.error import Error
from ...types import Response

def sync_detailed(sandbox_id: str, *, client: AuthenticatedClient) -> Response[Union[Any, Error]]:
    """Kill a sandbox

    Args:
        sandbox_id (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Union[Any, Error]]
    """
    ...

def sync(sandbox_id: str, *, client: AuthenticatedClient) -> Optional[Union[Any, Error]]:
    """Kill a sandbox

    Args:
        sandbox_id (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Union[Any, Error]
    """
    ...

async def asyncio_detailed(sandbox_id: str, *, client: AuthenticatedClient) -> Response[Union[Any, Error]]:
    """Kill a sandbox

    Args:
        sandbox_id (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Union[Any, Error]]
    """
    ...

async def asyncio(sandbox_id: str, *, client: AuthenticatedClient) -> Optional[Union[Any, Error]]:
    """Kill a sandbox

    Args:
        sandbox_id (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Union[Any, Error]
    """
    ...

