"""
This type stub file was generated by pyright.
"""

from typing import Optional, Union
from ...client import AuthenticatedClient
from ...models.error import Error
from ...models.sandbox_detail import SandboxDetail
from ...types import Response

def sync_detailed(sandbox_id: str, *, client: AuthenticatedClient) -> Response[Union[Error, SandboxDetail]]:
    """Get a sandbox by id

    Args:
        sandbox_id (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Union[Error, SandboxDetail]]
    """
    ...

def sync(sandbox_id: str, *, client: AuthenticatedClient) -> Optional[Union[Error, SandboxDetail]]:
    """Get a sandbox by id

    Args:
        sandbox_id (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Union[Error, SandboxDetail]
    """
    ...

async def asyncio_detailed(sandbox_id: str, *, client: AuthenticatedClient) -> Response[Union[Error, SandboxDetail]]:
    """Get a sandbox by id

    Args:
        sandbox_id (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Union[Error, SandboxDetail]]
    """
    ...

async def asyncio(sandbox_id: str, *, client: AuthenticatedClient) -> Optional[Union[Error, SandboxDetail]]:
    """Get a sandbox by id

    Args:
        sandbox_id (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Union[Error, SandboxDetail]
    """
    ...

