"""
This type stub file was generated by pyright.
"""

from typing import Optional, Union
from ...client import AuthenticatedClient
from ...models.error import Error
from ...models.resumed_sandbox import ResumedSandbox
from ...models.sandbox import Sandbox
from ...types import Response

def sync_detailed(sandbox_id: str, *, client: AuthenticatedClient, body: ResumedSandbox) -> Response[Union[Error, Sandbox]]:
    """Resume the sandbox

    Args:
        sandbox_id (str):
        body (ResumedSandbox):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Union[Error, Sandbox]]
    """
    ...

def sync(sandbox_id: str, *, client: AuthenticatedClient, body: ResumedSandbox) -> Optional[Union[Error, Sandbox]]:
    """Resume the sandbox

    Args:
        sandbox_id (str):
        body (ResumedSandbox):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Union[Error, Sandbox]
    """
    ...

async def asyncio_detailed(sandbox_id: str, *, client: AuthenticatedClient, body: ResumedSandbox) -> Response[Union[Error, Sandbox]]:
    """Resume the sandbox

    Args:
        sandbox_id (str):
        body (ResumedSandbox):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Union[Error, Sandbox]]
    """
    ...

async def asyncio(sandbox_id: str, *, client: AuthenticatedClient, body: ResumedSandbox) -> Optional[Union[Error, Sandbox]]:
    """Resume the sandbox

    Args:
        sandbox_id (str):
        body (ResumedSandbox):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Union[Error, Sandbox]
    """
    ...

