"""
This type stub file was generated by pyright.
"""

from typing import Optional, Union
from ...client import AuthenticatedClient
from ...models.error import Error
from ...models.new_sandbox import NewSandbox
from ...models.sandbox import Sandbox
from ...types import Response

def sync_detailed(*, client: AuthenticatedClient, body: NewSandbox) -> Response[Union[Error, Sandbox]]:
    """Create a sandbox from the template

    Args:
        body (NewSandbox):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Union[Error, Sandbox]]
    """
    ...

def sync(*, client: AuthenticatedClient, body: NewSandbox) -> Optional[Union[Error, Sandbox]]:
    """Create a sandbox from the template

    Args:
        body (NewSandbox):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Union[Error, Sandbox]
    """
    ...

async def asyncio_detailed(*, client: AuthenticatedClient, body: NewSandbox) -> Response[Union[Error, Sandbox]]:
    """Create a sandbox from the template

    Args:
        body (NewSandbox):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Union[Error, Sandbox]]
    """
    ...

async def asyncio(*, client: AuthenticatedClient, body: NewSandbox) -> Optional[Union[Error, Sandbox]]:
    """Create a sandbox from the template

    Args:
        body (NewSandbox):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Union[Error, Sandbox]
    """
    ...

