"""
This type stub file was generated by pyright.
"""

import json
import logging
from types import TracebackType
from typing import Optional
from httpx import Limits
from dataclasses import dataclass
from e2b.api.client.client import AuthenticatedClient
from e2b.connection_config import ConnectionConfig
from e2b.api.metadata import default_headers
from e2b.exceptions import AuthenticationException, RateLimitException, SandboxException
from e2b.api.client.types import Response

logger = ...
@dataclass
class SandboxCreateResponse:
    sandbox_id: str
    sandbox_domain: Optional[str]
    envd_version: str
    envd_access_token: str
    ...


def handle_api_exception(e: Response, default_exception_class: type[Exception] = ..., stack_trace: Optional[TracebackType] = ...): # -> AuthenticationException | RateLimitException | Exception:
    ...

class ApiClient(AuthenticatedClient):
    """
    The client for interacting with the E2B API.
    """
    def __init__(self, config: ConnectionConfig, require_api_key: bool = ..., require_access_token: bool = ..., limits: Optional[Limits] = ..., *args, **kwargs) -> None:
        ...
    


class AsyncApiClient(ApiClient):
    ...


