"""
This type stub file was generated by pyright.
"""

from typing import Any, AsyncGenerator, Optional
from e2b.envd.filesystem.filesystem_pb2 import WatchDirResponse
from e2b.sandbox.filesystem.watch_handle import FilesystemEvent
from e2b.sandbox_async.utils import OutputHandler

class AsyncWatchHandle:
    """
    Handle for watching a directory in the sandbox filesystem.

    Use `.stop()` to stop watching the directory.
    """
    def __init__(self, events: AsyncGenerator[WatchDirResponse, Any], on_event: OutputHandler[FilesystemEvent], on_exit: Optional[OutputHandler[Exception]] = ...) -> None:
        ...
    
    async def stop(self): # -> None:
        """
        Stop watching the directory.
        """
        ...
    


