"""
This type stub file was generated by pyright.
"""

from typing import Dict, List, Optional, Protocol, Union
from e2b.template.types import CopyItem

class DockerfFileFinalParserInterface(Protocol):
    """Protocol defining the final interface for Dockerfile parsing callbacks."""
    ...


class DockerfileParserInterface(Protocol):
    """Protocol defining the interface for Dockerfile parsing callbacks."""
    def run_cmd(self, command: Union[str, List[str]], user: Optional[str] = ...) -> DockerfileParserInterface:
        """Handle RUN instruction."""
        ...
    
    def copy(self, src: Union[str, List[CopyItem]], dest: Optional[str] = ..., force_upload: Optional[bool] = ..., user: Optional[str] = ..., mode: Optional[int] = ...) -> DockerfileParserInterface:
        """Handle COPY instruction."""
        ...
    
    def set_workdir(self, workdir: str) -> DockerfileParserInterface:
        """Handle WORKDIR instruction."""
        ...
    
    def set_user(self, user: str) -> DockerfileParserInterface:
        """Handle USER instruction."""
        ...
    
    def set_envs(self, envs: Dict[str, str]) -> DockerfileParserInterface:
        """Handle ENV instruction."""
        ...
    
    def set_start_cmd(self, start_cmd: str, ready_cmd: str) -> DockerfFileFinalParserInterface:
        """Handle CMD/ENTRYPOINT instruction."""
        ...
    


def parse_dockerfile(dockerfile_content_or_path: str, template_builder: DockerfileParserInterface) -> str:
    """Parse a Dockerfile and convert it to Template SDK format.

    Args:
        dockerfile_content_or_path: Either the Dockerfile content as a string,
                                   or a path to a Dockerfile file
        template_builder: Interface providing template builder methods

    Returns:
        The base image from the Dockerfile

    Raises:
        ValueError: If the Dockerfile is invalid or unsupported
    """
    ...

