"""
This type stub file was generated by pyright.
"""

class ReadyCmd:
    def __init__(self, cmd: str) -> None:
        ...
    
    def get_cmd(self): # -> str:
        ...
    


def wait_for_port(port: int): # -> ReadyCmd:
    """Generate a command to wait for a port to be available."""
    ...

def wait_for_url(url: str, status_code: int = ...): # -> ReadyCmd:
    """Generate a command to wait for a URL to return a specific status code."""
    ...

def wait_for_process(process_name: str): # -> ReadyCmd:
    """Generate a command to wait for a process to be running."""
    ...

def wait_for_file(filename: str): # -> ReadyCmd:
    """Generate a command to wait for a file to exist."""
    ...

def wait_for_timeout(timeout: int): # -> ReadyCmd:
    """Generate a command to wait for a specified duration."""
    ...

