"""
This type stub file was generated by pyright.
"""

from types import FrameType, TracebackType
from typing import List, Optional, Union

def read_dockerignore(context_path: str) -> List[str]:
    ...

def calculate_files_hash(src: str, dest: str, context_path: str, ignore_patterns: Optional[List[str]] = ..., stack_trace: Optional[TracebackType] = ...) -> str:
    ...

def strip_ansi_escape_codes(text: str) -> str:
    """Strip ANSI escape codes from a string. Source: https://github.com/chalk/ansi-regex/blob/main/index.js"""
    ...

def get_caller_frame(depth: int) -> Optional[FrameType]:
    """Get the caller frame. Skip this function (first frame)."""
    ...

def get_caller_directory(depth: int) -> Optional[str]:
    """Get the directory of the file that called this function."""
    ...

def pad_octal(mode: int) -> str:
    ...

def get_build_step_index(step: str, stack_traces_length: int) -> int:
    ...

def read_gcp_service_account_json(context_path: str, path_or_content: Union[str, dict]) -> str:
    ...

