"""
This type stub file was generated by pyright.
"""

from collections.abc import Mapping
from typing import Any, TypeVar
from attrs import define as _attrs_define
from ..models.aws_registry_type import AWSRegistryType

T = TypeVar("T", bound="AWSRegistry")
@_attrs_define
class AWSRegistry:
    """
    Attributes:
        aws_access_key_id (str): AWS Access Key ID for ECR authentication
        aws_region (str): AWS Region where the ECR registry is located
        aws_secret_access_key (str): AWS Secret Access Key for ECR authentication
        type_ (AWSRegistryType): Type of registry authentication
    """
    aws_access_key_id: str
    aws_region: str
    aws_secret_access_key: str
    type_: AWSRegistryType
    additional_properties: dict[str, Any] = ...
    def to_dict(self) -> dict[str, Any]:
        ...
    
    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        ...
    
    @property
    def additional_keys(self) -> list[str]:
        ...
    
    def __getitem__(self, key: str) -> Any:
        ...
    
    def __setitem__(self, key: str, value: Any) -> None:
        ...
    
    def __delitem__(self, key: str) -> None:
        ...
    
    def __contains__(self, key: str) -> bool:
        ...
    


