"""
This type stub file was generated by pyright.
"""

import datetime
from collections.abc import Mapping
from typing import Any, TYPE_CHECKING, TypeVar, Union
from uuid import UUID
from attrs import define as _attrs_define
from ..types import Unset
from ..models.identifier_masking_details import IdentifierMaskingDetails
from ..models.team_user import TeamUser

if TYPE_CHECKING:
    ...
T = TypeVar("T", bound="CreatedTeamAPIKey")
@_attrs_define
class CreatedTeamAPIKey:
    """
    Attributes:
        created_at (datetime.datetime): Timestamp of API key creation
        id (UUID): Identifier of the API key
        key (str): Raw value of the API key
        mask (IdentifierMaskingDetails):
        name (str): Name of the API key
        created_by (Union['TeamUser', None, Unset]):
        last_used (Union[None, Unset, datetime.datetime]): Last time this API key was used
    """
    created_at: datetime.datetime
    id: UUID
    key: str
    mask: IdentifierMaskingDetails
    name: str
    created_by: Union[TeamUser, None, Unset] = ...
    last_used: Union[None, Unset, datetime.datetime] = ...
    additional_properties: dict[str, Any] = ...
    def to_dict(self) -> dict[str, Any]:
        ...
    
    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        ...
    
    @property
    def additional_keys(self) -> list[str]:
        ...
    
    def __getitem__(self, key: str) -> Any:
        ...
    
    def __setitem__(self, key: str, value: Any) -> None:
        ...
    
    def __delitem__(self, key: str) -> None:
        ...
    
    def __contains__(self, key: str) -> bool:
        ...
    


