"""
This type stub file was generated by pyright.
"""

from collections.abc import Mapping
from typing import Any, TypeVar
from attrs import define as _attrs_define

T = TypeVar("T", bound="DiskMetrics")
@_attrs_define
class DiskMetrics:
    """
    Attributes:
        device (str): Device name
        filesystem_type (str): Filesystem type (e.g., ext4, xfs)
        mount_point (str): Mount point of the disk
        total_bytes (int): Total space in bytes
        used_bytes (int): Used space in bytes
    """
    device: str
    filesystem_type: str
    mount_point: str
    total_bytes: int
    used_bytes: int
    additional_properties: dict[str, Any] = ...
    def to_dict(self) -> dict[str, Any]:
        ...
    
    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        ...
    
    @property
    def additional_keys(self) -> list[str]:
        ...
    
    def __getitem__(self, key: str) -> Any:
        ...
    
    def __setitem__(self, key: str, value: Any) -> None:
        ...
    
    def __delitem__(self, key: str) -> None:
        ...
    
    def __contains__(self, key: str) -> bool:
        ...
    


