"""
This type stub file was generated by pyright.
"""

from collections.abc import Mapping
from typing import Any, TypeVar
from attrs import define as _attrs_define
from ..models.gcp_registry_type import GCPRegistryType

T = TypeVar("T", bound="GCPRegistry")
@_attrs_define
class GCPRegistry:
    """
    Attributes:
        service_account_json (str): Service Account JSON for GCP authentication
        type_ (GCPRegistryType): Type of registry authentication
    """
    service_account_json: str
    type_: GCPRegistryType
    additional_properties: dict[str, Any] = ...
    def to_dict(self) -> dict[str, Any]:
        ...
    
    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        ...
    
    @property
    def additional_keys(self) -> list[str]:
        ...
    
    def __getitem__(self, key: str) -> Any:
        ...
    
    def __setitem__(self, key: str, value: Any) -> None:
        ...
    
    def __delitem__(self, key: str) -> None:
        ...
    
    def __contains__(self, key: str) -> bool:
        ...
    


