"""
This type stub file was generated by pyright.
"""

from collections.abc import Mapping
from typing import Any, TypeVar
from attrs import define as _attrs_define
from ..models.general_registry_type import GeneralRegistryType

T = TypeVar("T", bound="GeneralRegistry")
@_attrs_define
class GeneralRegistry:
    """
    Attributes:
        password (str): Password to use for the registry
        type_ (GeneralRegistryType): Type of registry authentication
        username (str): Username to use for the registry
    """
    password: str
    type_: GeneralRegistryType
    username: str
    additional_properties: dict[str, Any] = ...
    def to_dict(self) -> dict[str, Any]:
        ...
    
    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        ...
    
    @property
    def additional_keys(self) -> list[str]:
        ...
    
    def __getitem__(self, key: str) -> Any:
        ...
    
    def __setitem__(self, key: str, value: Any) -> None:
        ...
    
    def __delitem__(self, key: str) -> None:
        ...
    
    def __contains__(self, key: str) -> bool:
        ...
    


