"""
This type stub file was generated by pyright.
"""

from collections.abc import Mapping
from typing import Any, TypeVar
from attrs import define as _attrs_define

T = TypeVar("T", bound="IdentifierMaskingDetails")
@_attrs_define
class IdentifierMaskingDetails:
    """
    Attributes:
        masked_value_prefix (str): Prefix used in masked version of the token or key
        masked_value_suffix (str): Suffix used in masked version of the token or key
        prefix (str): Prefix that identifies the token or key type
        value_length (int): Length of the token or key
    """
    masked_value_prefix: str
    masked_value_suffix: str
    prefix: str
    value_length: int
    additional_properties: dict[str, Any] = ...
    def to_dict(self) -> dict[str, Any]:
        ...
    
    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        ...
    
    @property
    def additional_keys(self) -> list[str]:
        ...
    
    def __getitem__(self, key: str) -> Any:
        ...
    
    def __setitem__(self, key: str, value: Any) -> None:
        ...
    
    def __delitem__(self, key: str) -> None:
        ...
    
    def __contains__(self, key: str) -> bool:
        ...
    


