"""
This type stub file was generated by pyright.
"""

from collections.abc import Mapping
from typing import Any, TYPE_CHECKING, TypeVar
from attrs import define as _attrs_define
from ..models.sandbox_log import SandboxLog
from ..models.sandbox_log_entry import SandboxLogEntry

if TYPE_CHECKING:
    ...
T = TypeVar("T", bound="SandboxLogs")
@_attrs_define
class SandboxLogs:
    """
    Attributes:
        log_entries (list['SandboxLogEntry']): Structured logs of the sandbox
        logs (list['SandboxLog']): Logs of the sandbox
    """
    log_entries: list[SandboxLogEntry]
    logs: list[SandboxLog]
    additional_properties: dict[str, Any] = ...
    def to_dict(self) -> dict[str, Any]:
        ...
    
    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        ...
    
    @property
    def additional_keys(self) -> list[str]:
        ...
    
    def __getitem__(self, key: str) -> Any:
        ...
    
    def __setitem__(self, key: str, value: Any) -> None:
        ...
    
    def __delitem__(self, key: str) -> None:
        ...
    
    def __contains__(self, key: str) -> bool:
        ...
    


