"""
This type stub file was generated by pyright.
"""

import datetime
from collections.abc import Mapping
from typing import Any, TypeVar
from attrs import define as _attrs_define

T = TypeVar("T", bound="TeamMetric")
@_attrs_define
class TeamMetric:
    """Team metric with timestamp

    Attributes:
        concurrent_sandboxes (int): The number of concurrent sandboxes for the team
        sandbox_start_rate (float): Number of sandboxes started per second
        timestamp (datetime.datetime): Timestamp of the metric entry
    """
    concurrent_sandboxes: int
    sandbox_start_rate: float
    timestamp: datetime.datetime
    additional_properties: dict[str, Any] = ...
    def to_dict(self) -> dict[str, Any]:
        ...
    
    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        ...
    
    @property
    def additional_keys(self) -> list[str]:
        ...
    
    def __getitem__(self, key: str) -> Any:
        ...
    
    def __setitem__(self, key: str, value: Any) -> None:
        ...
    
    def __delitem__(self, key: str) -> None:
        ...
    
    def __contains__(self, key: str) -> bool:
        ...
    


