"""
This type stub file was generated by pyright.
"""

from collections.abc import Mapping
from typing import Any, TypeVar, Union
from attrs import define as _attrs_define
from ..types import Unset

T = TypeVar("T", bound="TemplateStep")
@_attrs_define
class TemplateStep:
    """Step in the template build process

    Attributes:
        type_ (str): Type of the step
        args (Union[Unset, list[str]]): Arguments for the step
        files_hash (Union[Unset, str]): Hash of the files used in the step
        force (Union[Unset, bool]): Whether the step should be forced to run regardless of the cache Default: False.
    """
    type_: str
    args: Union[Unset, list[str]] = ...
    files_hash: Union[Unset, str] = ...
    force: Union[Unset, bool] = ...
    additional_properties: dict[str, Any] = ...
    def to_dict(self) -> dict[str, Any]:
        ...
    
    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        ...
    
    @property
    def additional_keys(self) -> list[str]:
        ...
    
    def __getitem__(self, key: str) -> Any:
        ...
    
    def __setitem__(self, key: str, value: Any) -> None:
        ...
    
    def __delitem__(self, key: str) -> None:
        ...
    
    def __contains__(self, key: str) -> bool:
        ...
    


