"""
This type stub file was generated by pyright.
"""

from collections.abc import Mapping
from typing import Any, TypeVar, Union
from attrs import define as _attrs_define
from ..types import Unset

T = TypeVar("T", bound="TemplateBuildRequest")
@_attrs_define
class TemplateBuildRequest:
    """
    Attributes:
        dockerfile (str): Dockerfile for the template
        alias (Union[Unset, str]): Alias of the template
        cpu_count (Union[Unset, int]): CPU cores for the sandbox
        memory_mb (Union[Unset, int]): Memory for the sandbox in MiB
        ready_cmd (Union[Unset, str]): Ready check command to execute in the template after the build
        start_cmd (Union[Unset, str]): Start command to execute in the template after the build
        team_id (Union[Unset, str]): Identifier of the team
    """
    dockerfile: str
    alias: Union[Unset, str] = ...
    cpu_count: Union[Unset, int] = ...
    memory_mb: Union[Unset, int] = ...
    ready_cmd: Union[Unset, str] = ...
    start_cmd: Union[Unset, str] = ...
    team_id: Union[Unset, str] = ...
    additional_properties: dict[str, Any] = ...
    def to_dict(self) -> dict[str, Any]:
        ...
    
    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        ...
    
    @property
    def additional_keys(self) -> list[str]:
        ...
    
    def __getitem__(self, key: str) -> Any:
        ...
    
    def __setitem__(self, key: str, value: Any) -> None:
        ...
    
    def __delitem__(self, key: str) -> None:
        ...
    
    def __contains__(self, key: str) -> bool:
        ...
    


