"""
This type stub file was generated by pyright.
"""

from collections.abc import Mapping
from typing import Any, TypeVar, Union
from attrs import define as _attrs_define
from ..types import Unset

T = TypeVar("T", bound="TemplateUpdateRequest")
@_attrs_define
class TemplateUpdateRequest:
    """
    Attributes:
        public (Union[Unset, bool]): Whether the template is public or only accessible by the team
    """
    public: Union[Unset, bool] = ...
    additional_properties: dict[str, Any] = ...
    def to_dict(self) -> dict[str, Any]:
        ...
    
    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        ...
    
    @property
    def additional_keys(self) -> list[str]:
        ...
    
    def __getitem__(self, key: str) -> Any:
        ...
    
    def __setitem__(self, key: str, value: Any) -> None:
        ...
    
    def __delitem__(self, key: str) -> None:
        ...
    
    def __contains__(self, key: str) -> bool:
        ...
    


