"""
This type stub file was generated by pyright.
"""

from collections.abc import Mapping
from typing import Any, TypeVar, Union
from attrs import define as _attrs_define
from ..types import Unset

T = TypeVar("T", bound="TemplateBuildFileUpload")
@_attrs_define
class TemplateBuildFileUpload:
    """
    Attributes:
        present (bool): Whether the file is already present in the cache
        url (Union[Unset, str]): Url where the file should be uploaded to
    """
    present: bool
    url: Union[Unset, str] = ...
    additional_properties: dict[str, Any] = ...
    def to_dict(self) -> dict[str, Any]:
        ...
    
    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        ...
    
    @property
    def additional_keys(self) -> list[str]:
        ...
    
    def __getitem__(self, key: str) -> Any:
        ...
    
    def __setitem__(self, key: str, value: Any) -> None:
        ...
    
    def __delitem__(self, key: str) -> None:
        ...
    
    def __contains__(self, key: str) -> bool:
        ...
    


